<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Gearman Monitor</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="Tales Galvão">

        <!-- Bootstrap -->
        <link href="/monitor/public/css/bootstrap.css" rel="stylesheet" media="screen">
        <link href="/monitor/public/css/bootstrap.css" rel="stylesheet">
        <link href="/monitor/public/css/bootstrap-responsive.css" rel="stylesheet">
        <link rel="stylesheet" href="/monitor/public/css/style.css" type="text/css"/>

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="/qa/public/js/html5shiv.js"></script>
        <![endif]-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>