            <!-- SCRIPTS -->
            <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
            <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.0/jquery-ui.min.js"></script>
            <!-- Le javascript
            ================================================== -->
            <!-- Placed at the end of the document so the pages load faster -->
            <script src="public/js/jquery.js"></script>
            <script src="public/js/bootstrap-transition.js"></script>
            <script src="public/js/bootstrap-alert.js"></script>
            <script src="public/js/bootstrap-modal.js"></script>
            <script src="public/js/bootstrap-dropdown.js"></script>
            <script src="public/js/bootstrap-scrollspy.js"></script>
            <script src="public/js/bootstrap-tab.js"></script>
            <script src="public/js/bootstrap-tooltip.js"></script>
            <script src="public/js/bootstrap-popover.js"></script>
            <script src="public/js/bootstrap-button.js"></script>
            <script src="public/js/bootstrap-collapse.js"></script>
            <script src="public/js/bootstrap-carousel.js"></script>
            <script src="public/js/bootstrap-typeahead.js"></script>