<link rel="stylesheet" href="/qa/public/css/style.css" type="text/css"/>
<div id="header"></div>

<div id="container">
	<div id="status-container" class="status-container">
		<iframe width="100%" height="100%" id="content" src="http://192.168.0.202/monitor/index/showStatus"></iframe>
	</div>
</div>

<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.0/jquery-ui.min.js"></script>
<script type="text/javascript">
	window.setInterval(function(){$("#content").attr('src','http://192.168.0.202/monitor/index/showStatus');},1000);
</script>